INSERT INTO
  `local_countries` (
    `id`,
    `name`,
    `payment_url`,
    `currency`,
    `pro_price`
  )
VALUES
  (
    2,
    'Nigeria',
    'https://flutterwave.com/pay/footy-amigo-nigeria',
    'NGN',
    10500.00
  ),
  (
    3,
    'Benin',
    'https://flutterwave.com/pay/footy-amigo-benin',
    'CFA',
    14000.00
  ),
  (
    4,
    'South Africa',
    'https://flutterwave.com/pay/footy-amigo-sa',
    'ZAR',
    375.00
  ),
  (
    5,
    'Kenya',
    'https://flutterwave.com/pay/footy-amigo-kenya',
    'KES',
    2760.00
  ),
  (
    6,
    'Ghana',
    'https://flutterwave.com/pay/footy-amigo-ghana',
    'GHS',
    152.00
  ),
  (
    7,
    'Uganda',
    'https://flutterwave.com/pay/footy-amigo-uganda',
    'UGX',
    88240.00
  ),
  (
    8,
    'Tanzania',
    'https://flutterwave.com/pay/footy-amigo-tanzania',
    'TZS',
    57900.00
  ),
  (
    9,
    'Morocco',
    'https://flutterwave.com/pay/footy-amigo-morocco',
    'MAD',
    230.00
  ),
  (
    10,
    'Botswana',
    'https://flutterwave.com/pay/footy-amigo-botswana',
    'BWP',
    285.00
  );