import pandas as pd
from datetime import datetime
# {'a': pd.Series(dtype='dtype='"Int64"''),
result_fields = {
    # '_id': pd.Series(dtype='object'),
    #  'id': "Int64",

    #  'added_time': "Int64",
    #  'aggregate_id': "Int64",
    'away_cards': "Int64",
    'away_cards_1h': "Int64",
    'away_cards_2h': "Int64",
    'away_clean_sheets': bool,
    'away_corners': "Int64",
    'away_corners_1h': "Int64",
    'away_corners_2h': "Int64",
    #  'away_formation': str,
    'away_fts': bool,
    'away_goal_difference': "Int64",
    'away_goals': "Int64",
    'away_goals_1h': "Int64",
    'away_goals_2h': "Int64",
    'away_goals_after_70': bool,
    'away_goals_after_75': bool,
    'goals_before_30': bool,
    'away_goals_before_30': bool,
    "home_goals_before_30": bool,
    'most_goals_1h': bool,
    'most_goals_2h': bool,
    'away_id': "Int64",
    #  'away_logo': str,
    #  'away_name': str,
    'away_points': "Int64",
    #  'away_position': "Int64",
    'away_red_cards': "Int64",
    'away_scored_first': bool,
    'away_win': bool,
    'away_win_ht': bool,
    'away_yellow_cards': "Int64",
    'btts': bool,
    'btts_1h': bool,
    'btts_2h': bool,
    'btts_o25': bool,
    'btts_or_o25': bool,
    #  'cards': object,
    'cards_1h': "Int64",
    'cards_2h': "Int64",
    'corner_timings_all': object,
    'corner_timings_away': object,
    'corner_timings_home': object,
    'corner_timings_mean': float,
    #  'corners': object,
    'corners_1h': "Int64",
    'corners_2h': "Int64",
    'corners_between_0_10': bool,
    'corners_between_0_10_away': bool,
    'corners_between_0_10_home': bool,
    'corners_between_0_15': bool,
    'corners_between_35_45': bool,
    'corners_between_40_45': bool,
    'corners_between_75_90': bool,
    'corners_between_80_90': bool,
    'corners_between_85_90': bool,
    #  'country_id': "Int64",
    #  'country_name': str,
    #  'date': "datetime64[ns]",
    #  'date_time': "datetime64[ns]",
    'draw': bool,
    'draw_ht': bool,
    'et_score': str,
    #  'events': object,
    #  'extra_minute': "Int64",
    'first_away_corner': float,
    'first_away_goal': float,
    'first_home_corner': float,
    'first_home_goal': float,
    'first_total_corner': float,
    'first_total_goal': float,
    'fixture_id': "Int64",
    #  'fixture_name': str,
    #  'flag_emoji': str,
    'ft_corner': str,
    'ft_score': str,
    'goal_timings_all': object,
    'goal_timings_away': object,
    'goal_timings_home': object,
    'goal_timings_mean': float,
    'goals_after_75': bool,
    #  'goals': object,
    'goals_1h': "Int64",
    'goals_2h': "Int64",
    'goals_after_70': bool,
    'goals_between_0_10': bool,
    'goals_between_0_15': bool,
    'goals_between_0_15_away': bool,
    'goals_between_0_15_home': bool,
    'goals_between_35_45': bool,
    'goals_between_40_45': bool,
    'goals_between_75_90': bool,
    'goals_between_80_90': bool,
    'goals_between_85_90': bool,
    #  'group_id': "Int64",
    'home_cards': "Int64",
    'home_cards_1h': "Int64",
    'home_clean_sheets': bool,
    'home_corners': "Int64",
    'home_corners_1h': "Int64",
    #  'home_formation': str,
    'home_fts': bool,
    'home_goal_difference': "Int64",
    'home_goals': "Int64",
    'home_goals_1h': "Int64",
    'home_goals_after_70': bool,
    'home_id': "Int64",
    #  'home_logo': str,
    #  'home_name': str,
    'home_points': "Int64",
    #  'home_position': str,
    'home_red_cards': "Int64",
    'home_scored_first': bool,
    'home_win': bool,
    'home_win_ht': bool,
    'home_yellow_cards': "Int64",
    'ht_corner': str,
    'ht_score': str,
    #  'injury_time': "Int64",
    #  'iso': str,
    #  'league_id': "Int64",
    #  'league_name': str,
    #  'live_odds': object,
    #  'minute': "Int64",
    'no_away_goals': bool,
    'no_cards': bool,
    'no_corners': bool,
    'no_goals': bool,
    'no_goals_1h': bool,
    'no_goals_2h': bool,
    'no_home_goals': bool,
    'o05_away_cards_1h': bool,
    'o05_away_goals_1h': bool,
    'o05_cards_1h': bool,
    'o05_corners_1h': bool,
    'o05_goals_1h': bool,
    'o05_home_cards_1h': bool,
    'o05_home_goals_1h': bool,
    'o05_away_cards_2h': bool,
    'o05_away_goals_2h': bool,
    'o05_cards_2h': bool,
    'o05_corners_2h': bool,
    'o05_goals_2h': bool,
    'o05_home_cards_2h': bool,
    'o05_home_goals_2h': bool,
    'o05_away_cards': bool,
    'o05_away_goals': bool,
    'o05_away_red_cards': bool,
    'o05_away_yellow_cards': bool,
    'o05_home_cards': bool,
    'o05_home_goals': bool,
    'o05_home_red_cards': bool,
    'o05_home_yellow_cards': bool,
    'o105_corners': bool,
    'o115_corners': bool,
    'o125_corners': bool,
    'o15_away_cards_1h': bool,
    'o15_away_corners_1h': bool,
    'o15_away_goals_1h': bool,
    'o15_cards_1h': bool,
    'o15_corners_1h': bool,
    'o15_goals_1h': bool,
    'o15_home_cards_1h': bool,
    'o15_home_corners_1h': bool,
    'o15_home_goals_1h': bool,
    'o15_away_cards_2h': bool,
    'o15_away_corners_2h': bool,
    'o15_away_goals_2h': bool,
    'o15_cards_2h': bool,
    'o15_corners_2h': bool,
    'o15_goals_2h': bool,
    'o15_home_cards_2h': bool,
    'o15_home_corners_2h': bool,
    'o15_home_goals_2h': bool,
    'o15_away_cards': bool,
    'o15_away_goals': bool,
    'o15_away_red_cards': bool,
    'o15_away_yellow_cards': bool,
    'o15_goals': bool,
    'o15_home_cards': bool,
    'o15_home_goals': bool,
    'o15_home_red_cards': bool,
    'o15_home_yellow_cards': bool,
    'o25_away_corners_1h': bool,
    'o25_cards_1h': bool,
    'o25_corners_1h': bool,
    'o25_home_corners_1h': bool,
    'o25_away_corners_2h': bool,
    'o25_cards_2h': bool,
    'o25_corners_2h': bool,
    'o25_home_corners_2h': bool,
    'o25_away_cards': bool,
    'o25_away_corners': bool,
    'o25_away_goals': bool,
    'o25_away_red_cards': bool,
    'o25_away_yellow_cards': bool,
    'o25_cards': bool,
    'o25_goals': bool,
    'o25_home_cards': bool,
    'o25_home_corners': bool,
    'o25_home_goals': bool,
    'o25_home_red_cards': bool,
    'o25_home_yellow_cards': bool,
    'o35_away_corners_1h': bool,
    'o35_corners_1h': bool,
    'o35_home_corners_1h': bool,
    'o35_away_corners_2h': bool,
    'o35_corners_2h': bool,
    'o35_home_corners_2h': bool,
    'o35_away_cards': bool,
    'o35_away_corners': bool,
    'o35_cards': bool,
    'o35_goals': bool,
    'o35_home_cards': bool,
    'o35_home_corners': bool,
    'o45_away_corners_1h': bool,
    'o45_corners_1h': bool,
    'o45_home_corners_1h': bool,
    'o45_away_corners_2h': bool,
    'o45_corners_2h': bool,
    'o45_home_corners_2h': bool,
    'o45_away_corners': bool,
    'o45_cards': bool,
    'o45_goals': bool,
    'o45_home_corners': bool,
    'o55_corners_1h': bool,
    'o55_corners_2h': bool,
    'o55_away_corners': bool,
    'o55_cards': bool,
    'o55_corners': bool,
    'o55_goals': bool,
    'o55_home_corners': bool,
    'o65_away_corners': bool,
    'o65_cards': bool,
    'o65_corners': bool,
    'o65_home_corners': bool,
    'o75_away_corners': bool,
    'o75_corners': bool,
    'o75_home_corners': bool,
    'o85_corners': bool,
    'o95_corners': bool,
    #  'peak_odds': object,
    #  'pre_odds': object,
    #  'probability': object,
    'ps_score': str,
    #  'referee_id': "Int64",
    #  'round_id': "Int64",
    #  'season_id': "Int64",
    #  'second': "Int64",
    #  'stage_id': "Int64",
    #  'stats': object,
    'status': str,
    #  'status_words': str,
    #  'time': str,
    'timestamp': "Int64",
    #  'venue_id': "Int64",
    #  'weather': object,
    #  'winner_id': "Int64",
    'home_goals_2h': "Int64",
    'total_goals': "Int64",
    'total_corners': "Int64",
    'total_cards': "Int64",
    'home_cards_2h': "Int64",
    'home_corners_2h': "Int64"
}


meanable = [
    'added_time',

    'away_cards',
    'away_cards_1h',
    'away_cards_2h',
    'away_clean_sheets',
    'away_corners',
    'away_corners_1h',
    'away_corners_2h',
    'away_fts',
    'away_goal_difference',
    'away_goals',
    'away_goals_1h',
    'away_goals_2h',
    'away_goals_after_70',
    'away_id',
    'away_points',
    'away_position',
    'away_red_cards',
    'away_scored_first',
    'away_win',
    'away_win_ht',
    'away_yellow_cards',
    'btts',
    'btts_1h',
    'btts_2h',
    'btts_o25',
    'btts_or_o25',
    'cards_1h',
    'cards_2h',
    'corner_timings_mean',
    'corners_1h',
    'corners_2h',
    'corners_between_0_10',
    'corners_between_0_10_away',
    'corners_between_0_10_home',
    'corners_between_0_15',
    'corners_between_35_45',
    'corners_between_40_45',
    'corners_between_75_90',
    'corners_between_80_90',
    'corners_between_85_90',

    'draw',
    'draw_ht',
    'extra_minute',
    'first_away_corner',
    'first_away_goal',
    'first_home_corner',
    'first_home_goal',
    'first_total_corner',
    'first_total_goal',

    'goal_timings_mean',
    'goals_1h',
    'goals_2h',
    'goals_after_70',
    'goals_between_0_10',
    'goals_between_0_15',
    'goals_between_0_15_away',
    'goals_between_0_15_home',
    'goals_between_35_45',
    'goals_between_40_45',
    'goals_between_75_90',
    'goals_between_80_90',
    'goals_between_85_90',
    'group_id',
    'home_cards',
    'home_cards_1h',
    'home_clean_sheets',
    'home_corners',
    'home_corners_1h',
    'home_fts',
    'home_goal_difference',
    'home_goals',
    'home_goals_1h',
    'home_goals_after_70',

    'home_points',
    'home_red_cards',
    'home_scored_first',
    'home_win',
    'home_win_ht',
    'home_yellow_cards',
    'injury_time',

    'minute',
    'no_away_goals',
    'no_cards',
    'no_corners',
    'no_goals',
    'no_goals_1h',
    'no_goals_2h',
    'no_home_goals',
    'o05_away_cards_1h',
    'o05_away_goals_1h',
    'o05_cards_1h',
    'o05_corners_1h',
    'o05_goals_1h',
    'o05_home_cards_1h',
    'o05_home_goals_1h',
    'o05_away_cards_2h',
    'o05_away_goals_2h',
    'o05_cards_2h',
    'o05_corners_2h',
    'o05_goals_2h',
    'o05_home_cards_2h',
    'o05_home_goals_2h',
    'o05_away_cards',
    'o05_away_goals',
    'o05_away_red_cards',
    'o05_away_yellow_cards',
    'o05_home_cards',
    'o05_home_goals',
    'o05_home_red_cards',
    'o05_home_yellow_cards',
    'o105_corners',
    'o115_corners',
    'o125_corners',
    'o15_away_cards_1h',
    'o15_away_corners_1h',
    'o15_away_goals_1h',
    'o15_cards_1h',
    'o15_corners_1h',
    'o15_goals_1h',
    'o15_home_cards_1h',
    'o15_home_corners_1h',
    'o15_home_goals_1h',
    'o15_away_cards_2h',
    'o15_away_corners_2h',
    'o15_away_goals_2h',
    'o15_cards_2h',
    'o15_corners_2h',
    'o15_goals_2h',
    'o15_home_cards_2h',
    'o15_home_corners_2h',
    'o15_home_goals_2h',
    'o15_away_cards',
    'o15_away_goals',
    'o15_away_red_cards',
    'o15_away_yellow_cards',
    'o15_goals',
    'o15_home_cards',
    'o15_home_goals',
    'o15_home_red_cards',
    'o15_home_yellow_cards',
    'o25_away_corners_1h',
    'o25_cards_1h',
    'o25_corners_1h',
    'o25_home_corners_1h',
    'o25_away_corners_2h',
    'o25_cards_2h',
    'o25_corners_2h',
    'o25_home_corners_2h',
    'o25_away_cards',
    'o25_away_corners',
    'o25_away_goals',
    'o25_away_red_cards',
    'o25_away_yellow_cards',
    'o25_cards',
    'o25_goals',
    'o25_home_cards',
    'o25_home_corners',
    'o25_home_goals',
    'o25_home_red_cards',
    'o25_home_yellow_cards',
    'o35_away_corners_1h',
    'o35_corners_1h',
    'o35_home_corners_1h',
    'o35_away_corners_2h',
    'o35_corners_2h',
    'o35_home_corners_2h',
    'o35_away_cards',
    'o35_away_corners',
    'o35_cards',
    'o35_goals',
    'o35_home_cards',
    'o35_home_corners',
    'o45_away_corners_1h',
    'o45_corners_1h',
    'o45_home_corners_1h',
    'o45_away_corners_2h',
    'o45_corners_2h',
    'o45_home_corners_2h',
    'o45_away_corners',
    'o45_cards',
    'o45_goals',
    'o45_home_corners',
    'o55_corners_1h',
    'o55_corners_2h',
    'o55_away_corners',
    'o55_cards',
    'o55_corners',
    'o55_goals',
    'o55_home_corners',
    'o65_away_corners',
    'o65_cards',
    'o65_corners',
    'o65_home_corners',
    'o75_away_corners',
    'o75_corners',
    'o75_home_corners',
    'o85_corners',
    'o95_corners',
    'home_goals_2h',
    'total_goals',
    'total_corners',
    'total_cards',
    'home_cards_2h',
    'home_corners_2h']
