{
    "live_odds.sum_of_teams.dnb": "Live Odds - Sum Of Teams DNB",
    "live_odds.sum_of_teams.ft_result": "Live Odds - Sum Of Teams - FT Result",
    "live_odds.sum_of_teams.ht_result": "Live Odds - Sum Of Teams - HT Result",
    "live_odds.home.dnb": "Live Odds - Home DNB",
    "live_odds.home.ft_result": "Live Odds - Home - FT Result",
    "live_odds.home.ht_result": "Live Odds - Home - HT Result",
    "live_odds.away.dnb": "Live Odds - Away DNB",
    "live_odds.away.ft_result": "Live Odds - Away - FT Result",
    "live_odds.away.ht_result": "Live Odds - Away - HT Result",
    "live_odds.either_team.dnb": "Live Odds - Either Team DNB",
    "live_odds.either_team.ft_result": "Live Odds - Either Team - FT Result",
    "live_odds.either_team.ht_result": "Live Odds - Either Team - HT Result",
    "live_odds.favorite.dnb": "Live Odds - Favorite DNB",
    "live_odds.favorite.ft_result": "Live Odds - Favorite - FT Result",
    "live_odds.favorite.ht_result": "Live Odds - Favorite - HT Result",
    "live_odds.favorite_playing_home.dnb": "Live Odds - Favorite Playing Home DNB",
    "live_odds.favorite_playing_home.ft_result": "Live Odds - Favorite Playing Home - FT Result",
    "live_odds.favorite_playing_home.ht_result": "Live Odds - Favorite Playing Home - HT Result",
    "live_odds.favorite_playing_away.dnb": "Live Odds - Favorite Playing Away DNB",
    "live_odds.favorite_playing_away.ft_result": "Live Odds - Favorite Playing Away - FT Result",
    "live_odds.favorite_playing_away.ht_result": "Live Odds - Favorite Playing Away - HT Result",
    "live_odds.underdog.dnb": "Live Odds - Underdog DNB",
    "live_odds.underdog.ft_result": "Live Odds - Underdog - FT Result",
    "live_odds.underdog.ht_result": "Live Odds - Underdog - HT Result",
    "live_odds.underdog_playing_home.dnb": "Live Odds - Underdog Playing Home DNB",
    "live_odds.underdog_playing_home.ft_result": "Live Odds - Underdog Playing Home - FT Result",
    "live_odds.underdog_playing_home.ht_result": "Live Odds - Underdog Playing Home - HT Result",
    "live_odds.underdog_playing_away.dnb": "Live Odds - Underdog Playing Away DNB",
    "live_odds.underdog_playing_away.ft_result": "Live Odds - Underdog Playing Away - FT Result",
    "live_odds.underdog_playing_away.ht_result": "Live Odds - Underdog Playing Away - HT Result",
    "live_odds.winning_team.dnb": "Live Odds - Winning Team DNB",
    "live_odds.winning_team.ft_result": "Live Odds - Winning Team FT Result",
    "live_odds.winning_team.ht_result": "Live Odds - Winning Team - HT Result",
    "live_odds.losing_team.dnb": "Live Odds - Losing Team DNB",
    "live_odds.losing_team.ft_result": "Live Odds - Losing Team FT Result",
    "live_odds.losing_team.ht_result": "Live Odds - Losing Team - HT Result",
    "pre_odds.sum_of_teams.dnb": "Pre Odds - Sum Of Teams DNB",
    "pre_odds.sum_of_teams.ft_result": "Pre Odds - Sum Of Teams FT Result",
    "pre_odds.sum_of_teams.ht_result": "Pre Odds - Sum Of Teams - HT Result",
    "pre_odds.home.dnb": "Pre Odds - Home DNB",
    "pre_odds.home.ft_result": "Pre Odds - Home FT Result",
    "pre_odds.home.ht_result": "Pre Odds - Home - HT Result",
    "pre_odds.away.dnb": "Pre Odds - Away DNB",
    "pre_odds.away.ft_result": "Pre Odds - Away FT Result",
    "pre_odds.away.ht_result": "Pre Odds - Away - HT Result",
    "pre_odds.either_team.dnb": "Pre Odds - Either Team DNB",
    "pre_odds.either_team.ft_result": "Pre Odds - Either Team FT Result",
    "pre_odds.either_team.ht_result": "Pre Odds - Either Team - HT Result",
    "pre_odds.favorite.dnb": "Pre Odds - Favorite DNB",
    "pre_odds.favorite.ft_result": "Pre Odds - Favorite FT Result",
    "pre_odds.favorite.ht_result": "Pre Odds - Favorite - HT Result",
    "pre_odds.favorite_playing_home.dnb": "Pre Odds - Favorite Playing Home DNB",
    "pre_odds.favorite_playing_home.ft_result": "Pre Odds - Favorite Playing Home - FT Result",
    "pre_odds.favorite_playing_home.ht_result": "Pre Odds - Favorite Playing Home - HT Result",
    "pre_odds.favorite_playing_away.dnb": "Pre Odds - Favorite Playing Away DNB",
    "pre_odds.favorite_playing_away.ft_result": "Pre Odds - Favorite Playing Away - FT Result",
    "pre_odds.favorite_playing_away.ht_result": "Pre Odds - Favorite Playing Away - HT Result",
    "pre_odds.underdog.dnb": "Pre Odds - Underdog DNB",
    "pre_odds.underdog.ft_result": "Pre Odds - Underdog - FT Result",
    "pre_odds.underdog.ht_result": "Pre Odds - Underdog - HT Result",
    "pre_odds.underdog_playing_home.dnb": "Pre Odds - Underdog Playing Home DNB",
    "pre_odds.underdog_playing_home.ft_result": "Pre Odds - Underdog Playing Home - FT Result",
    "pre_odds.underdog_playing_home.ht_result": "Pre Odds - Underdog Playing Home - HT Result",
    "pre_odds.underdog_playing_away.dnb": "Pre Odds - Underdog Playing Away DNB",
    "pre_odds.underdog_playing_away.ft_result": "Pre Odds - Underdog Playing Away - FT Result",
    "pre_odds.underdog_playing_away.ht_result": "Pre Odds - Underdog Playing Away - HT Result",
    "pre_odds.winning_team.dnb": "Pre Odds - Winning Team DNB",
    "pre_odds.winning_team.ft_result": "Pre Odds - Winning Team - FT Result",
    "pre_odds.winning_team.ht_result": "Pre Odds - Winning Team - HT Result",
    "pre_odds.losing_team.dnb": "Pre Odds - Losing Team DNB",
    "pre_odds.losing_team.ft_result": "Pre Odds - Losing Team - FT Result",
    "pre_odds.losing_team.ht_result": "Pre Odds - Losing Team - HT Result",
}
