import Vue from "vue";
//Vue.component("NextIcon", FootyButton);
import NextIcon from "~/static/icons/next.svg";
import PrevIcon from "~/static/icons/prev.svg";
import GreenTickIcon from "~/static/icons/green-tick.svg";
import InfoIcon from "~/static/icons/info.svg";
import DownloadIcon from "~/static/icons/download.svg";
import StatsIcon from "~/static/icons/stats.svg";
import SettingsIcon from "~/static/icons/settings.svg";
import DateIcon from "~/static/icons/date.svg";
import SearchIcon from "~/static/icons/search.svg";
import LeagueIcon from "~/static/icons/league.svg";
import KeyboardIcon from "~/static/icons/keyboard.svg";
import PlayIcon from "~/static/icons/play.svg";
import HelpIcon from "~/static/icons/help.svg";
import CalendarIcon from "~/static/icons/calendar.svg";
import TrophyIcon from "~/static/icons/trophy.svg";
import PicksIcon from "~/static/icons/picks.svg";
import ResultsIcon from "~/static/icons/history-white.svg";
import TimerIcon from "~/static/icons/timer.svg";
import BallIcon from "~/static/icons/ball.svg";
import FlagIcon from "~/static/icons/flag.svg";
import RightIcon from "~/static/icons/right.svg";
import CheckIcon from "~/static/icons/check.svg";

Vue.component("NextIcon", NextIcon);
Vue.component("PrevIcon", PrevIcon);
Vue.component("DownloadIcon", DownloadIcon);
Vue.component("RightIcon", RightIcon);
Vue.component("CheckIcon", CheckIcon);

Vue.component("InfoIcon", InfoIcon);
Vue.component("GreenTickIcon", GreenTickIcon);
Vue.component("StatsIcon", StatsIcon);
Vue.component("SettingsIcon", SettingsIcon);
Vue.component("DateIcon", DateIcon);
Vue.component("SearchIcon", SearchIcon);
Vue.component("LeagueIcon", LeagueIcon);
Vue.component("KeyboardIcon", KeyboardIcon);
Vue.component("PlayIcon", PlayIcon);
Vue.component("HelpIcon", HelpIcon);
Vue.component("CalendarIcon", CalendarIcon);
Vue.component("TrophyIcon", TrophyIcon);
Vue.component("PicksIcon", PicksIcon);
Vue.component("ResultsIcon", ResultsIcon);
Vue.component("TimerIcon", TimerIcon);
Vue.component("BallIcon", BallIcon);
Vue.component("FlagIcon", FlagIcon);
