var flags = {
  'ac': { 'country_name': 'Ascension Island', 'flag': '🇦🇨' },
  'ad': { 'country_name': 'Andorra', 'flag': '🇦🇩' },
  'ae': { 'country_name': 'United Arab Emirates', 'flag': '🇦🇪' },
  'af': { 'country_name': 'Afghanistan', 'flag': '🇦🇫' },
  'ag': { 'country_name': 'Antigua & Barbuda', 'flag': '🇦🇬' },
  'al': { 'country_name': 'Albania', 'flag': '🇦🇱' },
  'am': { 'country_name': 'Armenia', 'flag': '🇦🇲' },
  'ao': { 'country_name': 'Angola', 'flag': '🇦🇴' },
  'aq': { 'country_name': 'Antarctica', 'flag': '🇦🇶' },
  'ar': { 'country_name': 'Argentina', 'flag': '🇦🇷' },
  'as': { 'country_name': 'American Samoa', 'flag': '🇦🇸' },
  'at': { 'country_name': 'Austria', 'flag': '🇦🇹' },
  'au': { 'country_name': 'Australia', 'flag': '🇦🇺' },
  'aw': { 'country_name': 'Aruba', 'flag': '🇦🇼' },
  'ax': { 'country_name': 'Åland Islands', 'flag': '🇦🇽' },
  'az': { 'country_name': 'Azerbaijan', 'flag': '🇦🇿' },
  'ba': { 'country_name': 'Bosnia & Herzegovina', 'flag': '🇧🇦' },
  'bb': { 'country_name': 'Barbados', 'flag': '🇧🇧' },
  'bd': { 'country_name': 'Bangladesh', 'flag': '🇧🇩' },
  'be': { 'country_name': 'Belgium', 'flag': '🇧🇪' },
  'bf': { 'country_name': 'Burkina Faso', 'flag': '🇧🇫' },
  'bg': { 'country_name': 'Bulgaria', 'flag': '🇧🇬' },
  'bh': { 'country_name': 'Bahrain', 'flag': '🇧🇭' },
  'bi': { 'country_name': 'Burundi', 'flag': '🇧🇮' },
  'bj': { 'country_name': 'Benin', 'flag': '🇧🇯' },
  'bl': { 'country_name': 'St. Barthélemy', 'flag': '🇧🇱' },
  'bm': { 'country_name': 'Bermuda', 'flag': '🇧🇲' },
  'bn': { 'country_name': 'Brunei', 'flag': '🇧🇳' },
  'bo': { 'country_name': 'Bolivia', 'flag': '🇧🇴' },
  'bq': { 'country_name': 'Caribbean Netherlands', 'flag': '🇧🇶' },
  'br': { 'country_name': 'Brazil', 'flag': '🇧🇷' },
  'bs': { 'country_name': 'Bahamas', 'flag': '🇧🇸' },
  'bt': { 'country_name': 'Bhutan', 'flag': '🇧🇹' },
  'bv': { 'country_name': 'Bouvet Island', 'flag': '🇧🇻' },
  'bw': { 'country_name': 'Botswana', 'flag': '🇧🇼' },
  'by': { 'country_name': 'Belarus', 'flag': '🇧🇾' },
  'bz': { 'country_name': 'Belize', 'flag': '🇧🇿' },
  'ca': { 'country_name': 'Canada', 'flag': '🇨🇦' },
  'cc': { 'country_name': 'Cocos (Keeling) Islands', 'flag': '🇨🇨' },
  'cd': { 'country_name': 'Congo - Kinshasa', 'flag': '🇨🇩' },
  'cf': { 'country_name': 'Central African Republic', 'flag': '🇨🇫' },
  'cg': { 'country_name': 'Congo - Brazzaville', 'flag': '🇨🇬' },
  'ch': { 'country_name': 'Switzerland', 'flag': '🇨🇭' },
  'ci': { 'country_name': 'Côte d’Ivoire', 'flag': '🇨🇮' },
  'ck': { 'country_name': 'Cook Islands', 'flag': '🇨🇰' },
  'cl': { 'country_name': 'Chile', 'flag': '🇨🇱' },
  'cm': { 'country_name': 'Cameroon', 'flag': '🇨🇲' },
  'cn': { 'country_name': 'China', 'flag': '🇨🇳' },
  'co': { 'country_name': 'Colombia', 'flag': '🇨🇴' },
  'cp': { 'country_name': 'Clipperton Island', 'flag': '🇨🇵' },
  'cr': { 'country_name': 'Costa Rica', 'flag': '🇨🇷' },
  'cu': { 'country_name': 'Cuba', 'flag': '🇨🇺' },
  'cv': { 'country_name': 'Cape Verde', 'flag': '🇨🇻' },
  'cw': { 'country_name': 'Curaçao', 'flag': '🇨🇼' },
  'cx': { 'country_name': 'Christmas Island', 'flag': '🇨🇽' },
  'cy': { 'country_name': 'Cyprus', 'flag': '🇨🇾' },
  'cz': { 'country_name': 'Czechia', 'flag': '🇨🇿' },
  'de': { 'country_name': 'Germany', 'flag': '🇩🇪' },
  'dg': { 'country_name': 'Diego Garcia', 'flag': '🇩🇬' },
  'dj': { 'country_name': 'Djibouti', 'flag': '🇩🇯' },
  'dk': { 'country_name': 'Denmark', 'flag': '🇩🇰' },
  'dm': { 'country_name': 'Dominica', 'flag': '🇩🇲' },
  'do': { 'country_name': 'Dominican Republic', 'flag': '🇩🇴' },
  'dz': { 'country_name': 'Algeria', 'flag': '🇩🇿' },
  'ea': { 'country_name': 'Ceuta & Melilla', 'flag': '🇪🇦' },
  'ec': { 'country_name': 'Ecuador', 'flag': '🇪🇨' },
  'ee': { 'country_name': 'Estonia', 'flag': '🇪🇪' },
  'eg': { 'country_name': 'Egypt', 'flag': '🇪🇬' },
  'eh': { 'country_name': 'Western Sahara', 'flag': '🇪🇭' },
  'er': { 'country_name': 'Eritrea', 'flag': '🇪🇷' },
  'es': { 'country_name': 'Spain', 'flag': '🇪🇸' },
  'et': { 'country_name': 'Ethiopia', 'flag': '🇪🇹' },
  'eu': { 'country_name': 'European Union', 'flag': '🇪🇺' },
  'fi': { 'country_name': 'Finland', 'flag': '🇫🇮' },
  'fj': { 'country_name': 'Fiji', 'flag': '🇫🇯' },
  'fk': { 'country_name': 'Falkland Islands', 'flag': '🇫🇰' },
  'fm': { 'country_name': 'Micronesia', 'flag': '🇫🇲' },
  'fo': { 'country_name': 'Faroe Islands', 'flag': '🇫🇴' },
  'fr': { 'country_name': 'France', 'flag': '🇫🇷' },
  'ga': { 'country_name': 'Gabon', 'flag': '🇬🇦' },
  'gb': { 'country_name': 'United Kingdom', 'flag': '🇬🇧' },
  'gd': { 'country_name': 'Grenada', 'flag': '🇬🇩' },
  'ge': { 'country_name': 'Georgia', 'flag': '🇬🇪' },
  'gf': { 'country_name': 'French Guiana', 'flag': '🇬🇫' },
  'gg': { 'country_name': 'Guernsey', 'flag': '🇬🇬' },
  'gh': { 'country_name': 'Ghana', 'flag': '🇬🇭' },
  'gi': { 'country_name': 'Gibraltar', 'flag': '🇬🇮' },
  'gl': { 'country_name': 'Greenland', 'flag': '🇬🇱' },
  'gm': { 'country_name': 'Gambia', 'flag': '🇬🇲' },
  'gn': { 'country_name': 'Guinea', 'flag': '🇬🇳' },
  'gp': { 'country_name': 'Guadeloupe', 'flag': '🇬🇵' },
  'gq': { 'country_name': 'Equatorial Guinea', 'flag': '🇬🇶' },
  'gr': { 'country_name': 'Greece', 'flag': '🇬🇷' },
  'gs': { 'country_name': 'South Georgia & South Sandwich Islands', 'flag': '🇬🇸' },
  'gt': { 'country_name': 'Guatemala', 'flag': '🇬🇹' },
  'gu': { 'country_name': 'Guam', 'flag': '🇬🇺' },
  'gw': { 'country_name': 'Guinea-Bissau', 'flag': '🇬🇼' },
  'gy': { 'country_name': 'Guyana', 'flag': '🇬🇾' },
  'hk': { 'country_name': 'Hong Kong SAR China', 'flag': '🇭🇰' },
  'hm': { 'country_name': 'Heard & McDonald Islands', 'flag': '🇭🇲' },
  'hn': { 'country_name': 'Honduras', 'flag': '🇭🇳' },
  'hr': { 'country_name': 'Croatia', 'flag': '🇭🇷' },
  'ht': { 'country_name': 'Haiti', 'flag': '🇭🇹' },
  'hu': { 'country_name': 'Hungary', 'flag': '🇭🇺' },
  'ic': { 'country_name': 'Canary Islands', 'flag': '🇮🇨' },
  'id': { 'country_name': 'Indonesia', 'flag': '🇮🇩' },
  'ie': { 'country_name': 'Ireland', 'flag': '🇮🇪' },
  'il': { 'country_name': 'Israel', 'flag': '🇮🇱' },
  'im': { 'country_name': 'Isle of Man', 'flag': '🇮🇲' },
  'in': { 'country_name': 'India', 'flag': '🇮🇳' },
  '10': { 'country_name': 'British Indian Ocean Territory', 'flag': '🇮🇴' },
  'iq': { 'country_name': 'Iraq', 'flag': '🇮🇶' },
  'ir': { 'country_name': 'Iran', 'flag': '🇮🇷' },
  'is': { 'country_name': 'Iceland', 'flag': '🇮🇸' },
  'it': { 'country_name': 'Italy', 'flag': '🇮🇹' },
  'je': { 'country_name': 'Jersey', 'flag': '🇯🇪' },
  'jm': { 'country_name': 'Jamaica', 'flag': '🇯🇲' },
  'jo': { 'country_name': 'Jordan', 'flag': '🇯🇴' },
  'jp': { 'country_name': 'Japan', 'flag': '🇯🇵' },
  'ke': { 'country_name': 'Kenya', 'flag': '🇰🇪' },
  'kg': { 'country_name': 'Kyrgyzstan', 'flag': '🇰🇬' },
  'kh': { 'country_name': 'Cambodia', 'flag': '🇰🇭' },
  'ki': { 'country_name': 'Kiribati', 'flag': '🇰🇮' },
  'km': { 'country_name': 'Comoros', 'flag': '🇰🇲' },
  'kn': { 'country_name': 'St. Kitts & Nevis', 'flag': '🇰🇳' },
  'kp': { 'country_name': 'North Korea', 'flag': '🇰🇵' },
  'kr': { 'country_name': 'South Korea', 'flag': '🇰🇷' },
  'kw': { 'country_name': 'Kuwait', 'flag': '🇰🇼' },
  'ky': { 'country_name': 'Cayman Islands', 'flag': '🇰🇾' },
  'kz': { 'country_name': 'Kazakhstan', 'flag': '🇰🇿' },
  'la': { 'country_name': 'Laos', 'flag': '🇱🇦' },
  'lb': { 'country_name': 'Lebanon', 'flag': '🇱🇧' },
  'lc': { 'country_name': 'St. Lucia', 'flag': '🇱🇨' },
  'lu': { 'country_name': 'Luxembourg', 'flag': '🇱🇺' },
  'lk': { 'country_name': 'Sri Lanka', 'flag': '🇱🇰' },
  'lr': { 'country_name': 'Liberia', 'flag': '🇱🇷' },
  'ls': { 'country_name': 'Lesotho', 'flag': '🇱🇸' },
  'lt': { 'country_name': 'Lithuania', 'flag': '🇱🇹' },
  'lv': { 'country_name': 'Latvia', 'flag': '🇱🇻' },
  'ly': { 'country_name': 'Libya', 'flag': '🇱🇾' },
  'ma': { 'country_name': 'Morocco', 'flag': '🇲🇦' },
  'mc': { 'country_name': 'Monaco', 'flag': '🇲🇨' },
  'md': { 'country_name': 'Moldova', 'flag': '🇲🇩' },
  'me': { 'country_name': 'Montenegro', 'flag': '🇲🇪' },
  'mf': { 'country_name': 'St. Martin', 'flag': '🇲🇫' },
  'mg': { 'country_name': 'Madagascar', 'flag': '🇲🇬' },
  'mh': { 'country_name': 'Marshall Islands', 'flag': '🇲🇭' },
  'mk': { 'country_name': 'North Macedonia', 'flag': '🇲🇰' },
  'ml': { 'country_name': 'Mali', 'flag': '🇲🇱' },
  'mm': { 'country_name': 'Myanmar (Burma)', 'flag': '🇲🇲' },
  'mn': { 'country_name': 'Mongolia', 'flag': '🇲🇳' },
  'mo': { 'country_name': 'Macao Sar China', 'flag': '🇲🇴' },
  'mp': { 'country_name': 'Northern Mariana Islands', 'flag': '🇲🇵' },
  'mq': { 'country_name': 'Martinique', 'flag': '🇲🇶' },
  'mr': { 'country_name': 'Mauritania', 'flag': '🇲🇷' },
  'ms': { 'country_name': 'Montserrat', 'flag': '🇲🇸' },
  'mt': { 'country_name': 'Malta', 'flag': '🇲🇹' },
  'mu': { 'country_name': 'Mauritius', 'flag': '🇲🇺' },
  'mv': { 'country_name': 'Maldives', 'flag': '🇲🇻' },
  'mw': { 'country_name': 'Malawi', 'flag': '🇲🇼' },
  'mx': { 'country_name': 'Mexico', 'flag': '🇲🇽' },
  'my': { 'country_name': 'Malaysia', 'flag': '🇲🇾' },
  'mz': { 'country_name': 'Mozambique', 'flag': '🇲🇿' },
  'na': { 'country_name': 'Namibia', 'flag': '🇳🇦' },
  'nc': { 'country_name': 'New Caledonia', 'flag': '🇳🇨' },
  'ne': { 'country_name': 'Niger', 'flag': '🇳🇪' },
  'nf': { 'country_name': 'Norfolk Island', 'flag': '🇳🇫' },
  'ng': { 'country_name': 'Nigeria', 'flag': '🇳🇬' },
  'ni': { 'country_name': 'Nicaragua', 'flag': '🇳🇮' },
  'nl': { 'country_name': 'Netherlands', 'flag': '🇳🇱' },
  'no': { 'country_name': 'Norway', 'flag': '🇳🇴' },
  'np': { 'country_name': 'Nepal', 'flag': '🇳🇵' },
  'nr': { 'country_name': 'Nauru', 'flag': '🇳🇷' },
  'nu': { 'country_name': 'Niue', 'flag': '🇳🇺' },
  'nz': { 'country_name': 'New Zealand', 'flag': '🇳🇿' },
  'om': { 'country_name': 'Oman', 'flag': '🇴🇲' },
  'pa': { 'country_name': 'Panama', 'flag': '🇵🇦' },
  'pe': { 'country_name': 'Peru', 'flag': '🇵🇪' },
  'pf': { 'country_name': 'French Polynesia', 'flag': '🇵🇫' },
  'pg': { 'country_name': 'Papua New Guinea', 'flag': '🇵🇬' },
  'ph': { 'country_name': 'Philippines', 'flag': '🇵🇭' },
  'pk': { 'country_name': 'Pakistan', 'flag': '🇵🇰' },
  'pl': { 'country_name': 'Poland', 'flag': '🇵🇱' },
  'pm': { 'country_name': 'St. Pierre & Miquelon', 'flag': '🇵🇲' },
  'pn': { 'country_name': 'Pitcairn Islands', 'flag': '🇵🇳' },
  'pr': { 'country_name': 'Puerto Rico', 'flag': '🇵🇷' },
  'ps': { 'country_name': 'Palestinian Territories', 'flag': '🇵🇸' },
  'pt': { 'country_name': 'Portugal', 'flag': '🇵🇹' },
  'pw': { 'country_name': 'Palau', 'flag': '🇵🇼' },
  'py': { 'country_name': 'Paraguay', 'flag': '🇵🇾' },
  'qa': { 'country_name': 'Qatar', 'flag': '🇶🇦' },
  're': { 'country_name': 'Réunion', 'flag': '🇷🇪' },
  'ro': { 'country_name': 'Romania', 'flag': '🇷🇴' },
  'rs': { 'country_name': 'Serbia', 'flag': '🇷🇸' },
  'ru': { 'country_name': 'Russia', 'flag': '🇷🇺' },
  'rw': { 'country_name': 'Rwanda', 'flag': '🇷🇼' },
  'sa': { 'country_name': 'Saudi Arabia', 'flag': '🇸🇦' },
  'sb': { 'country_name': 'Solomon Islands', 'flag': '🇸🇧' },
  'sc': { 'country_name': 'Seychelles', 'flag': '🇸🇨' },
  'sd': { 'country_name': 'Sudan', 'flag': '🇸🇩' },
  'se': { 'country_name': 'Sweden', 'flag': '🇸🇪' },
  'sg': { 'country_name': 'Singapore', 'flag': '🇸🇬' },
  'sh': { 'country_name': 'St. Helena', 'flag': '🇸🇭' },
  'si': { 'country_name': 'Slovenia', 'flag': '🇸🇮' },
  'sj': { 'country_name': 'Svalbard & Jan Mayen', 'flag': '🇸🇯' },
  'sk': { 'country_name': 'Slovakia', 'flag': '🇸🇰' },
  'sl': { 'country_name': 'Sierra Leone', 'flag': '🇸🇱' },
  'sm': { 'country_name': 'San Marino', 'flag': '🇸🇲' },
  'sn': { 'country_name': 'Senegal', 'flag': '🇸🇳' },
  'so': { 'country_name': 'Somalia', 'flag': '🇸🇴' },
  'sr': { 'country_name': 'Suricountry_name', 'flag': '🇸🇷' },
  'ss': { 'country_name': 'South Sudan', 'flag': '🇸🇸' },
  'st': { 'country_name': 'São Tomé & Príncipe', 'flag': '🇸🇹' },
  'sv': { 'country_name': 'El Salvador', 'flag': '🇸🇻' },
  'sx': { 'country_name': 'Sint Maarten', 'flag': '🇸🇽' },
  'sy': { 'country_name': 'Syria', 'flag': '🇸🇾' },
  'sz': { 'country_name': 'Eswatini', 'flag': '🇸🇿' },
  'ta': { 'country_name': 'Tristan Da Cunha', 'flag': '🇹🇦' },
  'tc': { 'country_name': 'Turks & Caicos Islands', 'flag': '🇹🇨' },
  'td': { 'country_name': 'Chad', 'flag': '🇹🇩' },
  'tf': { 'country_name': 'French Southern Territories', 'flag': '🇹🇫' },
  'tg': { 'country_name': 'Togo', 'flag': '🇹🇬' },
  'tj': { 'country_name': 'Tajikistan', 'flag': '🇹🇯' },
  'th': { 'country_name': 'Thailand', 'flag': '🇹🇭' },
  'vu': { 'country_name': 'Vanuatu', 'flag': '🇻🇺' },
  'tk': { 'country_name': 'Tokelau', 'flag': '🇹🇰' },
  'tl': { 'country_name': 'Timor-Leste', 'flag': '🇹🇱' },
  'tm': { 'country_name': 'Turkmenistan', 'flag': '🇹🇲' },
  'tn': { 'country_name': 'Tunisia', 'flag': '🇹🇳' },
  'to': { 'country_name': 'Tonga', 'flag': '🇹🇴' },
  'tr': { 'country_name': 'Turkey', 'flag': '🇹🇷' },
  'tt': { 'country_name': 'Trinidad & Tobago', 'flag': '🇹🇹' },
  'tv': { 'country_name': 'Tuvalu', 'flag': '🇹🇻' },
  'tw': { 'country_name': 'Taiwan', 'flag': '🇹🇼' },
  'tz': { 'country_name': 'Tanzania', 'flag': '🇹🇿' },
  'ua': { 'country_name': 'Ukraine', 'flag': '🇺🇦' },
  'ug': { 'country_name': 'Uganda', 'flag': '🇺🇬' },
  'um': { 'country_name': 'U.S. Outlying Islands', 'flag': '🇺🇲' },
  'un': { 'country_name': 'United Nations', 'flag': '🇺🇳' },
  'us': { 'country_name': 'United States', 'flag': '🇺🇸' },
  'uy': { 'country_name': 'Uruguay', 'flag': '🇺🇾' },
  'uz': { 'country_name': 'Uzbekistan', 'flag': '🇺🇿' },
  'va': { 'country_name': 'Vatican City', 'flag': '🇻🇦' },
  'vc': { 'country_name': 'St. Vincent & Grenadines', 'flag': '🇻🇨' },
  've': { 'country_name': 'Venezuela', 'flag': '🇻🇪' },
  'vg': { 'country_name': 'British Virgin Islands', 'flag': '🇻🇬' },
  'vi': { 'country_name': 'U.S. Virgin Islands', 'flag': '🇻🇮' },
  'vn': { 'country_name': 'Vietnam', 'flag': '🇻🇳' },
  'we': { 'country_name': 'Wallis & Futuna', 'flag': '🇼🇫' },
  'ws': { 'country_name': 'Samoa', 'flag': '🇼🇸' },
  'xk': { 'country_name': 'Kosovo', 'flag': '🇽🇰' },
  'ye': { 'country_name': 'Yemen', 'flag': '🇾🇪' },
  'yt': { 'country_name': 'Mayotte', 'flag': '🇾🇹' },
  'za': { 'country_name': 'South Africa', 'flag': '🇿🇦' },
  'zm': { 'country_name': 'Zambia', 'flag': '🇿🇲' },
  'zw': { 'country_name': 'Zimbabwe', 'flag': '🇿🇼' }
}

module.exports = flags